version: "3"
services:
  eth-node:
    container_name: eth-node
    image: "trufflesuite/ganache-cli:v6.4.3"
    command: "-e 100000000 -l 0x888888 -d -h 0.0.0.0"
    ports:
      - "8545:8545"
  pyevm-backend-db:
    container_name: pyevm-backend-db
    image: ekristen/leveldb
    ports:
      - "2012:2012"
  abctoken-env:
    container_name: abctoken-env
    image: "abctoken-env:Latest"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src"
    network_mode: "host"
    command: "tail -f /dev/null"
