#! /bin/bash

docker rm -f eth-node
if [ ! "$(docker ps -q -f name=eth-node)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=eth-node)" ]; then
        # cleanup
        docker rm -f eth-node
    fi
fi
docker-compose up -d eth-node